### ISSUE TITLE
How to build it on Mingw64/MSYS2 ?

### ISSUE THREAD

**Issue by abdulbadii** [khallebal/haiku-elkirtasse#1]
I need Elkirtasse for Winndows but don't know how to build that on Mingw64/MSYS2.
Could you give the instructions in clear steps ?

**Comment by khallebal** [comment]
You don't have to build it yourself you can get it from the site of its author
http://elkirtasse.sourceforge.net/index.php/menu-down-all/down-elkirtasse/78-down-elkirtasse
I only made a copy of its source code here to make it compile under Haiku.
